[package]
name = "aoc_202x"
version = "0.1.0"
edition = "2024"
authors = ["Your Name <your@email.com>"]

[dependencies]
anyhow = "1.0.93"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
itertools = "0.14"
ureq = "3.1.4"
winnow = "0.7"
